### Add a book
POST http://localhost:3000/books
Content-Type: application/json

{ "title": "Dune", "author": "Frank Herbert" }

### Get all books
GET http://localhost:3000/books

### Get one book
GET http://localhost:3000/books/1

### Full update (title + author + status)
PUT http://localhost:3000/books/1
Content-Type: application/json

{ "title": "Dune", "author": "Frank Herbert", "status": "reading" }

### Update status only (for the dropdown)
PATCH http://localhost:3000/books/1/status
Content-Type: application/json

{ "status": "finished...good book!" }

### Delete a book
DELETE http://localhost:3000/books/1
